name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Build with Gradle 
      run: |
        chmod +x gradlew
        ./gradlew test
      continue-on-error: true

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: 'android-34'

    - name: Set up emulator
      run: echo "no" | avdmanager create avd -n test -k 'system-images;android-34;google_apis;x86' --tag google_apis --abi x86

    - name: Start the emulator
      run: $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-audio -no-snapshot-load -no-snapshot-save -gpu swiftshader

    - name: Run Espresso tests
      run: |
        chmod +x gradlew
        ./gradlew connectedDebugAndroidTest